### ISSUE TITLE
Bibliography needs to be editable at the same time as the rest of the antiquarian details

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#105]
@peterbispham - is it possible to do inline adding of biblio entries in the edit form?

**Comment by acholyn** [comment]
Closing as this is sort of not relevant anymore - bibliographies have changed in how they are built and so technically this has been achieved since when editing an Antiquarian's introduction, if a bibliography item is mentioned, it will show up in the bibliography for that antiquarian.
