### ISSUE TITLE
Hiding and/or filtering options in Anonymous section

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#113]
There will be a lot of information being shown at once for each of the anonymous entries. 

First, each anonymous entry will have a lot of information being displayed at once. Our suggestion was to show just a line with minimal information with a + button in order to display more details if the user chooses so. History prefers to always show all the information. Perhaps we could by default display all the information associated to each entry with a - button so information can be hidden, or a "collapse all" option on top to hide all the details.

Another option that needs more discussion is to have a filtering option on the top of the anonymous page to filter by topic/antiquarian/date, etc. This needs more discussion and refinement.

**Comment by tcouch** [comment]
Can we order by reference number under topics?

**Comment by raquelalegre** [comment]
Closing this issue as not relevant anymore, and making a new one for the ordering problem.
