### ISSUE TITLE
Helper text in references

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#166]
Once there is an agreement on how original texts' reference are formatted, we can have an info line below the reference box to show what the format should be.

**Comment by tcouch** [comment]
@dgiordani agreed to supply suggested helper text for this and #99

**Comment by rmamarshall** [comment]
Hi @acholyn, @dgiordani, @apitta0188. As this is a very old requirement, it may be best to bring it up with the team again - I think we are now sufficiently familiar with project processes and formatting rules that this may no longer be necessary. 

For such guidance to be useful, it would have to be citing author AND work specific, which would mean either an unusably long list, or some system whereby once a citing author and work has been selected in the process of creating a new fragment / testimonium, the guidance is then tailored to that specific combination of author / work. 

However, as we keep adding citing authors / works to the database and have no closed list of these, we would also need to have some way of adding the appropriate guidance every time a new citing author / work is created. Again, this seems like a lot of work for not a great return.

**Comment by rmamarshall** [comment]
@acholyn @apitta0188 As we have already entered the majority of texts, I think this requirement can be closed.
