### ISSUE TITLE
Tick box to confirm no data needs to be entered in Apparatus Criticus

### ISSUE THREAD

**Issue by rmamarshall** [UCL/frrant#179]
**Is your feature request related to a problem? Please describe.**
Difficult to tell whether there is no information to put in the Apparatus Criticus box (i.e. if box has been intentionally left blank), or if fragment has been created andd Apparatus still needs to be entered.

**Describe the solution you'd like**
A tick box to confirm whether the Apparatus Criticus has intentionally been left blank.

**Describe alternatives you've considered**

**Additional context**

**Comment by raquelalegre** [comment]
Changes should be as follows:
- [ ] When creating a fragment, there should be a checkbox for users to confirm no app crit is going to be entered.
- [ ] When viewing a fragment with no app crit, there should be a message that states no app crit was entered as chosen by the user, rathen than just "None".
- [ ] When editing a fragment with no app crit, it should still be allowed for the user to add an app crit if needed.
