### ISSUE TITLE
Search substitutions

### ISSUE THREAD

**Issue by raquel-ucl** [UCL/frrant#20]
Specifically:
  * vul <-> vol
  * v <-> u
 
Antonino will provide a full list

**Comment by raquelalegre** [comment]
We've just had a chat about how to proceed. 

@tim-band is going to try to implement a simple solution so we can test its performance. He'll add to the search string that gets sent to Postgres all the possible replacements given by a shorter version of the list of substitutions (e.g. `u`<->`v`, `y`<->`i`, `adr`<->`arr`, `adt`<->`att`). We'll then see how it performs and if we need to do any database tuning. There might be some ideas in the blog post linked in #8. It might also be possible to explore how to implement #64.

I'll look into using ElasticSearch in a way that doesn't have a big impact in the current functioning of the database, but can still be used for the search, in case what Tim tests has poor performance. We might get away with a mirror of the postgres DB that we only use for the search functionality, which gets refreshed with a cronjob that runs a few times a day. That might make it still usable and performant, without us having to review all the data input and edition functionality to make sure we keep the ElasticSearch mirror up to date.

We still need to explore how this is going to work beyond the end of our contribution to the project, as it needs to be a solution with near 0 maintenance costs.

**Comment by raquelalegre** [comment]
@apitta0188 we have a question for you. From the list of substitutions above, the words to the right of the `:` are they examples or the actual list of substitutions you want? For example, if you just search for `u` do we need to return everything that contains both a `u` and a `v`, or should we focus specifically on finding texts containing `uua` or `uva` when you enter `uua` (and same with `ouis`/`ovis`, `auus`/`avus`)? Further example: if someone enters `uarro` on the text search box, do we also return texts containing `varro`?
