### ISSUE TITLE
Dynamic links from original texts, translations and app crit

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#201]
@rmamarshall requests in the testsheets feedback the dynamic links to also be implemented in the original text box, translation box, and app. crit. since it may be useful to signal passages that we have treated as separate fragments elsewhere.

@rmamarshall can you clarify? Shouldn't this case be covered by mentioning the related fragments from the commentary box? Our understanding was original text items and their translations should contain only the original text.

**Comment by acholyn** [comment]
essentially another implementation of #358 which is related to #390

**Comment by acholyn** [comment]
@rmamarshall would you say that the mentions functionality fulfils this functionality? If not, could you expand on what should be done
