### ISSUE TITLE
Consider using pre-commit and black/blue

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#273]
This combination works quite well. Pre-commit will not allow commits unless the new code version passes the black or blue tests. If it doesn't pass them, then black or blue will be run and the code will be automatically formatted. On second attempt to commit it will allow it as the changes will have been automatically made. Blue seems easier to configure than black is, so probably we should go with that one.

**Comment by tcouch** [comment]
I think we can close this now since we included pre-commit with Black in #272
