### ISSUE TITLE
The "unlink" option in a fragment's apposita section should only display in edit mode.

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#280]
At the moment it displays in view mode and that can be dangerous.

**Comment by tcouch** [comment]
Actually it looks like the unlink option appears in an Anonymous Fragment's Appositum Links section outside edit mode, but not in a Fragment's Apposita section. See [Anonynous 187](https://www.ucl.ac.uk/history/frrant/anonymous/187/) for example

**Comment by raquelalegre** [comment]
Reopen until we get research team to approve.
