### ISSUE TITLE
Symbol picker problems

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#284]
It works fine on edit mode and for most of the font groups. However there are two problems:
* It doesn't allow selecting the "extra symbols" ":)" character anymore - there's just a tooltip that blinks when hoovering. It looks like if it was amongst other characters the ":)" character would work.
* It doesn't open when on non-edit mode. Maybe this was a design decision at some point, but we should allow rare symbols  to be entered in the Search bar.

**Comment by acholyn** [comment]
has been addressed at some point
