### ISSUE TITLE
Fix django warning emails

### ISSUE THREAD

**Issue by tcouch** [UCL/frrant#287]
Block unrecognised paths in nginx
Add server name (prod/preprod) to email subject.

**Comment by tcouch** [comment]
My current theory is that by listing server names other than www.ucl.ac.uk in the nginx rard.conf file, we were letting requests for random locations get through. If we restrict it to www.ucl.ac.uk, the location requested will have to be /history/frrant-preprod

Testing this tonight by changing:
```
- server_name www.ucl.ac.uk frra-app01p.ad.ucl.ac.uk frra-pp-10-00_524.gtm.ucl.ac.uk;
+ server_name www.ucl.ac.uk;
```

Let's see if we get any more emails in the next 24 hours.

**Comment by raquelalegre** [comment]
Seems like number of emails has gone down significantly last week.
