### ISSUE TITLE
Concordance: Identifier/Roman Numbers

### ISSUE THREAD

**Issue by dgiordani** [UCL/frrant#308]
**Is your feature request related to a problem? Please describe.**
As mentioned in the last meeting, there might be an issue with references to a concordance containing Roman numbers, since this might complicate their ordering in sequence.

**Describe the solution you'd like**
We were wondering if it might possible to have a double box in the identifier section in the concordance. In this way, we could use one box to enter the number we would like to have on actual display and the other to type the number we want the computer to process.

An example might help. If we need to add a concordance to CIL (Source) VI 1658 (Identifier), it would be helpful to have one identifier box in which we could type 'VI 1658' (actual display) and another in which we could enter '6.1658' (for the computer) to make sure this reference will follow 'V 1658 = 5.1658' and precede 'VII 1658 = 7.1658'.

**Describe alternatives you've considered**

**Additional context**

**Comment by tcouch** [comment]
Note to self: This library might prove useful: https://pypi.org/project/roman/
