### ISSUE TITLE
Problems with entering new texts and apparatus

### ISSUE THREAD

**Issue by apitta0188** [UCL/frrant#315]
**Describe the bug**
While editing/adding a new original text, there is just a blank space where the box to edit a new text should be (the same occurred during Christmas holidays)

**To Reproduce**
1. Go to 'Create new fragment', or 'add new OT'
2. Once the citing authors and works have been selected, it is impossible to add a new text (there is no box to do it)

**Comment by tcouch** [comment]
Hi @apitta0188 sorry, I didn't see this issue earlier. It seems to be working for me now, did this resolve itself?

**Comment by apitta0188** [comment]
Hi! Of course: the problem solved itself, actually.
Thank you, anyway (and no problem at all for the delay)!

all best,
antonino

________________________________
Da: Tom Couch ***@***.***>
Inviato: mercoledì 6 aprile 2022 11:58
A: UCL/frrant ***@***.***>
Cc: Pitta' Antonino (antonino.pitta) ***@***.***>; Mention ***@***.***>
Oggetto: Re: [UCL/frrant] Problems with entering new texts and apparatus (Issue #315)


Hi @apitta0188<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapitta0188&data=04%7C01%7Cantonino.pitta%40unicatt.it%7Cb00b495bfdb54d95f2ab08da17b41257%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C637848359413204964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I5MgtWYvJBtbpo1GrYcao%2BIa2cGZ4ZbbT%2Bz3BX%2FJbXw%3D&reserved=0> sorry, I didn't see this issue earlier. It seems to be working for me now, did this resolve itself?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUCL%2Ffrrant%2Fissues%2F315%23issuecomment-1090083145&data=04%7C01%7Cantonino.pitta%40unicatt.it%7Cb00b495bfdb54d95f2ab08da17b41257%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C637848359413204964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lj8HVJ9xoDeb7deDeVMy%2BDZ6aGZKH1BHDs4f75z1%2BWo%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASBZFSMQ77C3LDDE3OZRTK3VDVN5JANCNFSM5MYQPBQQ&data=04%7C01%7Cantonino.pitta%40unicatt.it%7Cb00b495bfdb54d95f2ab08da17b41257%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C637848359413204964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xCq7mdUviFjSuJolZvK8xnkrlH8%2FdNyZEOcKV0XSxig%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


[http://static.unicatt.it/ext-portale/FirmaOutlook.jpg]<http://www.unicatt.it/>
[http://static.unicatt.it/ext-portale/5xmille-firma-mail-scritta.jpg]
