### ISSUE TITLE
Text editor add space between lines in view mode

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#319]
Reported by @rmamarshall. When creating an original text in edit mode, a user sees a spacing between lines that looks reasonable. However, upon saving and being presented with the text in view mode, the editor seems to have added increased the space between each line. The team prefers to maintain the spacing between lines the edit mode shows.

**Comment by acholyn** [comment]
If this is still the case, would it be possible for someone to share a screenshot as the spacing looks the same on my own laptop

**Comment by rmamarshall** [comment]
@acholyn 
![image](https://github.com/UCL/frrant/assets/75932472/38f84e62-7296-46f5-8fd6-79f7918f98ce)
![image](https://github.com/UCL/frrant/assets/75932472/3069b34a-1f0b-4036-8f1f-980b96c1a411)

Between the first two lines and the rest of the passage, a space is added once the text editor (first image) is closed. The second line ends in a hard return. This automatic formatting should be removed, as many kinds of evidence, including poetry (every verse of which ends in a hard return) is currently displayed incorrectly.

**Comment by rmamarshall** [comment]
@acholyn Hi - realised I've mixed screenshots from the Original Text and Translation boxes, but the issue is the same in all text editor boxes - once text is saved, the automatic formatting function adds inappropriate spaces after hard returns.

**Comment by acholyn** [comment]
How's this?
<img width="422" alt="image" src="https://github.com/UCL/frrant/assets/72266023/8b2b5567-c3d5-4bec-aa9c-a2409fcdd821">
