### ISSUE TITLE
Document what can be done from the admin site

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#320]

**Comment by raquelalegre** [comment]
This is now becoming more important as I'm leaving in a month! I need to make sure this goes in this repo's wiki for future reference.

**Comment by acholyn** [comment]
This has been done already as the [wiki](https://github.com/UCL/frrant/wiki/Adding-new-symbols-to-the-symbol-picker) outlines how to add symbols and symbol groups, which is the main function afforded to researchers through the admin site
