### ISSUE TITLE
Allow multiple reference inputs when creating fragment

### ISSUE THREAD

**Issue by tcouch** [UCL/frrant#321]
Would it be possible to add additional boxes to the ‘Reference’ portion of the create fragment / anonymous fragment / testimonium pages?
Something like the following:
![image](https://user-images.githubusercontent.com/5113832/166813140-7d4af2e1-c0ff-4e24-8896-7dad2d86a900.png)

Where Reference 1 / 2 is an alphanumeric input (e.g. 2.3.4, p. 123), Reference 1 Source / 2 Source is an alphabetical input (e.g. Smith, Lindsay)
Reference order would be used as currently but be based on the Reference 1 entry.
The additional boxes could work like the concordance section (e.g. with an ‘add additional reference’ button).
This would allow us to refer to texts in multiple ways according to different editions.
As with many of our requests, it would be useful to know how much work would be involved in implementing this, and we could then assign an appropriate priority level.

**Comment by tcouch** [comment]
Question from @rmamarshall 

> 1.	Will there be a limit to the alternative references we can assign to texts (the new feature we discussed at our last meeting), or will this work like the existing ‘add concordance’ feature?

The more sustainable solution here would be to create a new model representing references which has a one to many relationship with original texts (one original text can have n references). So, in answer to the question, yes it would work in the same way as adding concordances.

**Comment by acholyn** [comment]
Handling existing references:
- [x] 1. Create new model to represent references. These would have FK pointing to the (anon)fragments/testimonia
- [x] 2. Migrate data to use new structure - go through all frags, take references and create new reference object pointing to the frags
- [x] 3. Remove reference property from fragment models but templates etc might be looking for the property so the best option might be to write a method which gets the info from the reference object to use as a property

Handling new references:
- [x] 4. set up templates to include multiple inputs for references, which will be created as objects - Django Formsets? Might be good to look at apparatus criticus templates etc.
- [x] 5. Abstract reference + original text form as a reusable component
- [ ] 6. Set up logic for default references (for now first can be default but this can be amended)
- [x] 7. ensure references can be edited
- [x] 8. Update update form for original texts to also use inline formset

**Comment by tcouch** [comment]
After discussing this issue in more detail, references should work as follows:
* Each original text should have a reference_order field which behaves exactly as the existing reference_order field does; i.e. a character field consisting of three zero-padded numbers separated by dots to facilitate ordering (e.g. 00012.00034.00056)
* This reference_order field does not need to be displayed on fragment detail pages (just editable on update pages)
* The new reference model should have two fields: editor (e.g. Jones) and reference (e.g. b7.c5.p6)
* Each original text can have many references associated with it
* Editor only needs to be displayed if there is more than one reference
