### ISSUE TITLE
Add symbol 03BD to symbol picker

### ISSUE THREAD

**Issue by tcouch** [UCL/frrant#327]
@rmamarshall asks "May we add a missing letter to the Greek section of the symbol picker? This appears on p. 5 of the [alphabetum character set]"

Character code is 03BD

**Comment by tcouch** [comment]
Added instructions on how to add new symbols to the wiki:
https://github.com/UCL/frrant/wiki/Adding-new-symbols-to-the-symbol-picker

**Comment by tcouch** [comment]
@rmamarshall I've added this to the production server.

**Comment by rmamarshall** [comment]
@tcouch Thank you - and thanks for the instructions in the wiki!
