### ISSUE TITLE
reference_order not being padded in database

### ISSUE THREAD

**Issue by acholyn** [UCL/frrant#344]
reference_order (for original texts) does not seem to undergo the `clean_reference_order` function to pad the numbers such that 10.17 would be stored as 00010.00017 in the database.

**Comment by tcouch** [comment]
I've discovered that explicitly running `form._post_clean()` during `OriginalTextUpdateView`'s `form_valid()` method fixes the problem, but _post_clean should have been triggered when the `form.is_valid` property is checked.

closing, but opening #348 to investigate why this is necessary
