### ISSUE TITLE
Original texts can be created with no reference

### ISSUE THREAD

**Issue by tcouch** [UCL/frrant#351]
When creating a new fragment, the form can be submitted with no references. The fragment is created successfully, but an error is raised when rendering the detail page because the reference_list property cannot deal with an original text having no references.

The solution would be to either:
* require all original texts to have at least one reference
* fix the reference_list property to allow for no references

**Comment by tcouch** [comment]
@rmamarshall do you think it would be preferable to allow original texts to be created without any references, or should be put controls in place to prevent that happening?

**Comment by rmamarshall** [comment]
@tcouch Every original text needs at least one reference - a block to prevent the creation of original texts without an entry in a reference field would be a good idea.
