### ISSUE TITLE
Set up pre-prod VM

### ISSUE THREAD

**Issue by raquel-ucl** [UCL/frrant#36]
This has now been requested by Wellesley.

Once it is ready, we'll have to:
* [x] Request SSH access for RITS team to HIS, including sudo permissions so we can run docker
* [x] Request firewall ports opened for external access to ns-core
* [ ] Request to create service id to Webops       
* [x] Email eligibility to request approval for url (www.ucl.ac.uk/history/frrant-dev?)
* [ ] Map url to pre-prod (request ns-core or platform integrations?)
* [ ] Request SSL certificate to Webops      
* [ ] Apply SSL cerificate  
* [ ] Request access for monitoring software and email alerts to HIS
* [ ] Set up UptimeRobot

**Comment by tcouch** [comment]
Now accessible publicly at https://frra-pp-10-00_524.gtm.ucl.ac.uk/frrant/ 
To do:
- [x] Add a big yellow banner saying development or pre-production to the top of every page
- [ ] Sort out the certificate
- [x] Sort out the URL mapping to ucl.ac.uk/history/frrant-preprod

**Comment by raquelalegre** [comment]
Now also accessible at https://www.ucl.ac.uk/history/frrant-preprod/, however all links take to the https://www.ucl.ac.uk/history/frrant version, which is a bit dangerous. Configuration needs changing as soon as possible.

**Comment by raquelalegre** [comment]
Configuration has been changed and both prod and pre-prod versions have been live for 2 weeks.
