### ISSUE TITLE
Adding apposita to anonymous fragments

### ISSUE THREAD

**Issue by rmamarshall** [UCL/frrant#374]
@tcouch 
Hi Tom, would it be possible to enable us to add apposita to anonymous fragments? Now that we have a better understanding of the material in the database, this feature might be useful afterall.

**Comment by tcouch** [comment]
Research group to discuss and get back to us.

**Comment by tcouch** [comment]
Hi Richard. When an anonymous fragment (A1) becomes an appositum to another anonymous fragment (A2), should it inherit any links that anonymous fragment A2 has to Antiquarians/Works/Fragments?

**Comment by tcouch** [comment]
Hi @rmamarshall I'm just looking into this issue now. Can I ask a few questions?

1. As above: Should anonymous fragments' apposita inherit their links to Antiquarians/Works/Fragments? (is apposit-ness a transitive relation?)
2. If an anonymous fragment with apposita is converted to an unlinked fragment, should those apposita also belong to the unlinked fragment?
3. If an unlinked fragment with apposita is converted to an anonymous fragment, should those apposita also belong to the anonymous fragment
4. Is the apposita relationship between two anonymous fragments a two-way thing; i.e., they are both apposita to each other; or is it one-way?

**Comment by rmamarshall** [comment]
@tcouch 
1. No, they should be treated as are apposita to fragments (i.e. no transferred links)
2. Yes, the link should be maintained (as this would only be a temporary status, i.e. Anonymous Fragment to unlinked to Fragment, or vice versa).
3. Yes.
4. One way.

If any of the above cause problems or the logic seems faulty, do let me know!
