### ISSUE TITLE
Searching Greek with diacriticals

### ISSUE THREAD

**Issue by rmamarshall** [UCL/frrant#377]
Searched of Greek text must employ the correct diacriticals to obtain results (e.g. διὰ not δια). Ideally, a search for δια should also return διὰ. 
Could this be implemented using symbol substitution, like the current search functionality for Latin text that use u/v, etc.?

**Comment by acholyn** [comment]
Potential solution: strip out all the accent unicodes with `unidecode` and use the base character in the search
