### ISSUE TITLE
Definite/Possible Clarity

### ISSUE THREAD

**Issue by acholyn** [UCL/frrant#379]
Currently links have a definite/possible attribute which might refer to a definite link to an Antiquarian and a work/book or just the Antiquarian. To give better visibility on which links are known to belong to an antiquarian/work/book. This could be done by adding new attributes for each link, being `definite_work` and `definite_book` and rename the current to `definite_antiquarian`. This could then be represented by different symbols/colours for the statuses.

**Comment by acholyn** [comment]
@rmamarshall  on the Fragment detail page, there are subheadings for "definite works and books", "possible works and books", "definite antiquarians" and "possible antiquarians", what would be the preferred way of displaying these relationships now? We could split antiquarian, work and book each into definite/possible or have more general "definite" and "possible" headings with symbols to indicate whether it's the antiquarian/work/book that is definite

**Comment by rmamarshall** [comment]
@acholyn Re: displaying relationships, my personal preference would be to split antiquarian, work and book each into definite/possible. I'm worried that signalling the staus of a relationship using headings and symbols / colours might be rather confusing, but if it is no more difficult to implement and you have an idea that you could mock up and show the rest of the team, it might be useful to hear their thoughts on this.
