### ISSUE TITLE
Moving links between works/books

### ISSUE THREAD

**Issue by acholyn** [UCL/frrant#380]
Currently the method to update a link's work/book is to create a new one with the right information. A solution could be to allow the user (in edit mode on the work/book page) to change this via an inline form with the dropdowns for work/book and whether this new allocation is definite or possible (see #379)

**Comment by rmamarshall** [comment]
@acholyn @tcouch Hi, to clarify my comments earlier, there are potentially several (possible) components that constitute a fragment's identity:

1. Possible Antiquarian
+ Possible work 
++ Possible book
++ Definite book [we may know that the fragment belongs to book three, but not the title of the work!]
OR
+ Definite work [we may know the title of the work, but not the author]
++ Possible book [we may know the fragment belongs to a work, but not which book of that work]
++ Definite book

2. Definite Antiquarian
+ Possible work 
++ Possible book
++ Definite book [we may know that the fragment belongs to book three, but not the title of the work]
OR
+ Definite work
++ Possible book [we may know the fragment belongs to a work, but not which book of that work]
++ Definite book

**Comment by acholyn** [comment]
would that mean if the link has a definite work/book you wouldn't want it to be possible to change it?

**Comment by rmamarshall** [comment]
@acholyn. If the Antiquarian is also definite, yes, it should not be possible to change the location of a fragment with definite work / book. 
If the antiquarian is only possible, but the work is definite, this can only mean that there are two works by two different authors that share the same title in the database, and we don't know to which one the fragment should be assigned. This also should not be changed _within_ an antiquarian entry.
If only a book is definite, it should only be possible to place the fragment in e.g. book three of any given work (though we might want to place it in two or more works simultaneously). I hope this makes sense!

The possible scenarios are:
1. Varro in book 2 of the _Disciplines_ says ...
Definite Antiquarian, Definite work, definite book.

2. Varro in the _Disciplines_ says ...
Definite Antiquarian, Definite work, unknown book (though we may was to assign a one or more possible books to the fragment).

3. Someone in book 2 of the _Disciplines_ says ...
This could be Varro or Nepos (so the fragment has two possible antiquarian identifications), but the work and book is definite, so can only appear in Book 2 of the Disciplines of Nepos and / or Book 2 of the Disciplines of Varro.

4. Someone in the _Liberal Arts_ says ...
Only the work is definite, multiple possible antiquarians and potential book attributions. However, if no known antiquarian used this title, we'd likely create a new entry in the antiquarians page specifically for this item (anonymous author of the _Liberal Arts_).

5. Someone in book 4 says ...
Only the book is definite, potentially multiple possible antiquarians and works, or simply an anonymous fragment.

6. Someone says ...
Potentially multiple possible antiquarian, work, and book identifications, or simply an anonymous fragment.

Luckily, examples 3-5 are very rare, but 6 is very common indeed.
