### ISSUE TITLE
Duplicating fragments

### ISSUE THREAD

**Issue by acholyn** [UCL/frrant#393]
Researchers would like the ability to duplicate a fragment with its original text (copy) and apparatus criticus but not the links. This would be a button available on the fragment page and could also be shown with the option of converting an Anon Frag to a normal one

**Comment by tcouch** [comment]
Would we want to add a copy_of attribute to the fragment so, for example, we can display this as a note on the detail page? In theory I suppose there could be more than one copy...
@rmamarshall what do you think? Would you need to track copies, or are you happy to just do this via @mentions in the commentary?

**Comment by acholyn** [comment]
@rmamarshall Would the duplicate retain the Antiquarian/work/book assignments or do you expect it to be an unlinked fragment?
And do you want the translations copied over as well?

**Comment by rmamarshall** [comment]
@acholyn Probably be best if an unlinked fragment - text, ap. crit., and translations should be duplicated, also if there is more than one original text. Commentary does not need to be duplicated.

**Comment by acholyn** [comment]
If duplicating an anonymous fragment, should it create an unlinked fragment or an anonymous one? or should this functionality not be included?

**Comment by rmamarshall** [comment]
@acholyn Probably best to create an unlinked fragment, as this offers most flexibility (can be turned into an anonymous fr. in the usual manner).

**Comment by tcouch** [comment]
@rmamarshall A few further questions:
1. Should we keep track of which fragments are duplicates of one another?
2. If so, would you like to see a list of duplicates on the page?
3. What should happen if someone edits the original texts/translations/concordances of one of the copies?
  a. Nothing - copies are allowed to diverge
  b. User sees a warning to remind them that the duplicate exists
  c. User has the option to apply changes to both copies when saving changes
  d. Changes are always automatically applied to both copies

**Comment by rmamarshall** [comment]
@tcouch @acholyn 

Should we keep track of which fragments are duplicates of one another?

> Yes please!

If so, would you like to see a list of duplicates on the page?

> Yes, this would be extremely useful. 

What should happen if someone edits the original texts/translations/concordances of one of the copies?
    a. Nothing - copies are allowed to diverge
    b. User sees a warning to remind them that the duplicate exists
    c. User has the option to apply changes to both copies when saving changes
    d. Changes are always automatically applied to both copies

> Probably best to go with b: we may want copies to diverge once an original has been duplicated. I am hesitant to implement c - while it may save time, it may also inadvertantly remove previous editorial work (especially if a fragment has been duplicated more than once). Options a and d are both dangerous.
