### ISSUE TITLE
New bibliography tools

### ISSUE THREAD

**Issue by rmamarshall** [UCL/frrant#412]
@acholyn. Hi Amanda, a couple of issues I've noticed when using the new bibliography tools:

There doesn't seem to be an ability to italicise text or use the other text-box features in the 'title' box of the new bibliography editor at the point when entries are added (correct formatting can currently only be implemented using the edit function, which isn't very obvious and takes several more clicks).

After deleting an item of bibliography added in error, the page displays incorrectly:

![image](https://github.com/UCL/frrant/assets/75932472/84885c9e-8a1b-45ba-8350-742684cce506)

**Comment by tcouch** [comment]
Looks like the cause of the page displaying incorrectly is the delete view is redirecting users to /bibliography/list rather than /bibliography

**Comment by tcouch** [comment]
Looks like we need to make sure the bibliography create form uses the quill editor

**Comment by acholyn** [comment]
@rmamarshall just to confirm - it's only the `title` field you'd like to have the extra formatting (italicisation) or all the fields?

**Comment by rmamarshall** [comment]
@acholyn Yes, just the title box (so long as the author field will take additional characters from the symbol picker).
