### ISSUE TITLE
Box for @ mentions

### ISSUE THREAD

**Issue by dgiordani** [UCL/frrant#413]
We have been told that commentaries are not going to be kept in the public version.

We would like to have a separate box below the apparatus criticus just for @ mentions.

**Comment by acholyn** [comment]
Would this be for the @ mentions in the commentary only? Would this not be resolved when we address #390 ?

**Comment by tcouch** [comment]
A.K.A Apparatus Fontium / Loci Similes
Like you may also be interested in... link to other items

**Comment by dgiordani** [comment]
Dear Tom.

Hope you're well! This is just a reply to your question below. Our idea was to have a special box underneath the text box and the apparatus criticus in order to be able to put all our @ mentions there. This is necessary because we are not sure whether the commentary box will eventually be there in our final version and we would like to be able to record @ mentions somewhere.

Also, Valentina mentioned that you received notifications I was doing something with the database last week. What happened was that I was inserting a fragment and after I typed something I cannot remember a series of straight lines appeared at the bottom of the text box. I tried to delete them but was unable to. Unfortunately I cannot remember which fragment it was but I'll have a proper look and report back to you.

Let me know if you need further info!

Best,
Domenico
________________________________

**Comment by acholyn** [comment]
Might be good to have a "public commentary" box which should still have the same @ mentions as the non public one. The public one should have a checkbox for public view. The mentions at the bottom of the page might not be particularly affected so long as we ensure unique values and the commentaries keep the same @ mentions. The non public commentary can then not be displayed on the website without removing it from the db

**Comment by acholyn** [comment]
Domenico, regarding your issues with the text editor, I've created a new issue #423 for it, do feel free to add any other information you feel is relevant

**Comment by acholyn** [comment]
@rmamarshall @dgiordani We have a proposed alternative solution: could you use the existing footnotes of the commentaries as the more length version and the main body as the "public" commentary? We could have a toggle so that you could see the full notes or just the public version (this would be unavailable to the general public, unless you decide otherwise) and we could strip out the indicators for the footnotes in the public version.

What do you think, would this be a reasonable solution?

**Comment by rmamarshall** [comment]
@acholyn I'm not sure that this would work, as that would then mean we'd need to add footnotes to the footnotes! We need these for adding additional material, references, tangential discussions etc. to the main body of the commentary; the @ mention box should really be something distinct.
