### ISSUE TITLE
New concordance structure

### ISSUE THREAD

**Issue by acholyn** [UCL/frrant#446]
Concordances will have a new structure, which will still essentially be a string but will be composed of different components in dropdown menus in order to construct it. There should also be some charfields to allow for outlier reference patterns. See the [document](https://github.com/UCL/frrant/files/14704144/Concordance.wireframe.docx) for a fleshed out wireframe regarding creation and searching.

The detail view should be like the search view, the items on the page are only displayed when a search has been done and the entries can be edited in place.

One aspect that will need further details is displaying the search results where there's no concordance available

**Comment by acholyn** [comment]
- might need to include code from `reference_order` to remove digit padding
-  this was done for ordering in the db, but is there a better way of doing it?
- [x] should check with the researchers if they want concordances attached to original texts or to the fragment/testimonium

**Comment by rmamarshall** [comment]
@acholyn @tcouch We discussed the issue of concordances at last Friday's research meeting, and wondered if we could add a new page to the site where options for the concordance could be added (like the 'Create new' pages that we use to add new works or citing sources). This would give us a lot more flexibility than relying on a spreadsheet to catch all the possible options we might need in advance (I can still supply this, but working through the 'part identifier' elements for some editions, it is apparent that a lot of information I'm adding will never be needed, though it is hard to anticipate what will and won't be redundant; it is also a very time-consuming process, as some collections include hundreds of authors who must all be individually catalogued using this approach).

What I think we would need is a box called 'edition identifier'; part identifier needed [tick yes or no]; 'add part identifier'; 'part identifier for alphabetisation'; bibliographical information (adding a link to the create bibliography tools). For existing entries, we would need an 'add new part identifier' option (plus 'part identifier for alphabetisation'). It would also be useful to see the full list of edition identifiers, and once an individual edition identifier is selected, a list of part identifiers (it would be best not to split this between pages, but present as a long page we could scroll through).

Is the above feasible, and would it represent a lot of new work?
