### ISSUE TITLE
Duplicating testimonia

### ISSUE THREAD

**Issue by acholyn** [UCL/frrant#450]
Expansion of #393 to include testimonia
- [x] allow conversion of unlinked to testimonium
- [x] expand duplicates list for duplicate testa
- [x] enable button 
- [x] update tests
  - [x] duplication
  - [x] conversion

**Comment by acholyn** [comment]
@rmamarshall when converting between testimonia and fragments (distinct from the duplication process), should the testimonium links be converted to apposita or should an unlinked fragment be created?

**Comment by rmamarshall** [comment]
@acholyn As far as I'm aware, apposita cannot currently be added to testimonia; if a fragment is converted to a testimonium, there should be a warning that apposita will be lost. I cannot see a scenario in which this would happen, however; we are more likely to duplicate a fragment first and then convert one of the pair into a testimonium.

**Comment by acholyn** [comment]
@rmamarshall Okidoke, and for converting a testimonium into a fragment, should it be unlinked or should those links be turned into apposita?
