### ISSUE TITLE
Endnotes in Antiquarian's introduction, fragments and testimonia

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#63]
Some of the Antiquarian introductions can be long essays of 20K words, and they'll need dynamic linking with ref numbers like [1], [2], etc.,  that update as you enter new references or remove others.

It's also needed this references can be dynamically linked to other elements in the database. For example, if there's an endnote for a fragment, and then the fragment order changes, the endnotes will need updating accordingly.

These endnotes would be specially useful for the publication, so the public can see the references.

A Javascript plugin can be made for this to work, but it will be time consuming. 

Plan B with Hypothesis post processing doesn't sound appealing.

Update 27th Nov: this means a footnote to a specific piece of text

**Comment by acholyn** [comment]
Update: see new issue #392

**Comment by acholyn** [comment]
closed in favour of new issue #392
