### ISSUE TITLE
Search with *

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#65]
Users should find "Varro" search results if they type:
* *rro
* Va*
* va*o

**Comment by tcouch** [comment]
In addition from #297: "It would be extremely useful to have the ability to construct searches like pro*ur (to find proferretur), and also, if possible, something like profe??etur (where ? would stand for a single unknown character, thus only returning words of the required 'shape')."

**Comment by tcouch** [comment]
Update from research meeting 04/04/2022: By default a keyword matches any part of a string. Can we add a tick box to make this an exact whole word match; e.g. "sed" matches "Amicus Plato, sed magis amica veritas" but not "possedere".

**Comment by tcouch** [comment]
Above request reiterated in today's meeting with "ara" being another example; e.g. matching "ara maxima" and not apparatus
