### ISSUE TITLE
Add new category of symbols to the symbol picker

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#70]
Antonino will send more info, but we need to add these IPA symbols: 
* 1D17 to 01DC in page 2
* 01DD to 02B8 in page 3

We should show them how to add them themselves on the admin screen so they see it's possible. Not sure they have included this in the test cases.

For reference, here are the Alphabetum font's docs:

http://guindo.pntic.mec.es/~jmag0042/ALPHABETUM_manual.pdf

http://guindo.pntic.mec.es/~jmag0042/ALPHABETUM_chart.pdf

**Comment by rmamarshall** [comment]
@acholyn @apitta0188 This looks like an issue with adding Alphabetum characters to the symbol picker, so should be relatively straight forward. Perhaps it would be best to have a document explaining how to do this so that we can add them as needed, rather than try to anticipate future need.

**Comment by acholyn** [comment]
@rmamarshall does [this wiki entry](https://github.com/UCL/frrant/wiki/Adding-new-symbols-to-the-symbol-picker) help?

If I'm understanding correctly, the characters exist in the font and have codes, they just need to be added to the picker, whereas #24 is an earlier stage and those need to be added to the actual font?

**Comment by acholyn** [comment]
closing in favour of #448 as this issue now concerns adding specific characters to the font
